Sync .github files from main

diff --git a/.github/workflows/src-data-change.yml b/.github/workflows/src-data-change.yml
--- a/.github/workflows/src-data-change.yml
+++ b/.github/workflows/src-data-change.yml
@@ -178,9 +178,9 @@ jobs:
           # python -c 'import cmipld; cmipld.map_current("emd");cmipld.get("emd:model_family/_graph.json")';
           mkdocs build -f "$GITHUB_WORKSPACE/src/mkdocs/mkdocs.yml"
 
-          BUILD_DIR="$GITHUB_WORKSPACE/src/mkdocs/site"
-          if [ ! -d "$BUILD_DIR" ]; then BUILD_DIR="$GITHUB_WORKSPACE/site"; fi
-          if [ ! -d "$BUILD_DIR" ]; then echo "Error: no built site dir"; exit 1; fi
+          BUILD_DIR="$GITHUB_WORKSPACE/src/mkdocs/build"
+          if [ ! -d "$BUILD_DIR" ]; then BUILD_DIR="$GITHUB_WORKSPACE/duild"; fi
+          if [ ! -d "$BUILD_DIR" ]; then echo "Error: no build dir"; exit 1; fi
 
           rm -rf "$GITHUB_WORKSPACE/src" "$GITHUB_WORKSPACE/mkdocs"
           [ -d "$GITHUB_WORKSPACE/docs" ] && rm -rf "$GITHUB_WORKSPACE/docs"
